### PR TITLE
update #75: localize calendar and save the selected lang

### PR DESCRIPTION
**Pull request by pawelFelcyn**
This pr refers to https://dev.azure.com/survey-project/Survey/_boards/board/t/Survey%20Team/Issues/?workitem=75 and adds the following:
- the calendar in the survey sending policy screen is localized 
- the selected language is remembered for the browser

### CODE REVIEW

**Comment by wgrzesik** [comment]
image

image

- center it verticaly
- choose either capital or small letter for language choice
- consider making the checkbox smaller

**Comment by wgrzesik** [comment]
image

- center the hamburger button vertically

**Comment by wgrzesik** [comment]
I belive that the setting the language for calendar is not working correctly. 
After choosing Englidh, when I switch to another tab from Surveys and then return to Surveys, the calendar is in Polish.

**Comment by wgrzesik** [comment]
Wherever there is black font color, it should be changed to dark gray. For example names of the months and days in the calendar, name of the language selected.

**Comment by pawelFelcyn** [comment]
> image
> 
> image
> 
> * center it verticaly
> * choose either capital or small letter for language choice
> * consider making the checkbox smaller

By "consider making the checkbox smaller" you mean the "check" icon, or the dropdown editor?

**Comment by wgrzesik** [comment]
> > image
> > image
> > 
> > * center it verticaly
> > * choose either capital or small letter for language choice
> > * consider making the checkbox smaller
> 
> By "consider making the checkbox smaller" you mean the "check" icon, or the dropdown editor?
> 
> "choose either capital or small letter for language choice" I was thinking about this and for me this also looks at least strangely. But this is because of the grama, actually. In Polish we name languages with a small letter, in English with a capital one. Another solution I've considered is displaying all the languages' names in a currently selected language. But this is also not a good idea, because the user can potentially not know what language he/she wants to pick. I don't know tbh...

I mean the dropdown editor.

Make both languages with capital letters, that will look clean and uniform.

**Comment by pawelFelcyn** [comment]
It maybe could be done better, when it comes to the CSS, but I really was not able to make this "cleaner". I mean there is this ugly "margin" property. Also, I rescaled the dropdown horizontally. Let me know @wgrzesik  if now it looks better and if you accept. 

The bug with the language not being loaded after changing the tab is fixed.

**Comment by wgrzesik** [comment]
> Wherever there is black font color, it should be changed to dark gray. For example names of the months and days in the calendar, name of the language selected.

add this

**Comment by pawelFelcyn** [comment]
> > Wherever there is black font color, it should be changed to dark gray. For example names of the months and days in the calendar, name of the language selected.
> 
> add this

sorry for forgetting this, I've just added

**Pull request merged**
